[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[shell]
program = "/bin/fish"
# args = ["--login"]

[env]
term = "xterm-256color"

